# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/packages/rtckit" # Location of package manifests
    registries: "*"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/packages/rtckit-node" # Location of package manifests
    registries: "*"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/apps/basic" # Location of package manifests
    registries: "*"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/apps/embedded-ingest-demo" # Location of package manifests
    registries: "*"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "weekly"
- package-ecosystem: "npm" # See documentation for possible values
    directory: "/apps/gvcdemo" # Location of package manifests
    registries: "*"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "weekly"
- package-ecosystem: "npm" # See documentation for possible values
    directory: "/apps/ingest-demo" # Location of package manifests
    registries: "*"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "weekly"
- package-ecosystem: "npm" # See documentation for possible values
    directory: "/apps/rtckit-node-demo" # Location of package manifests
    registries: "*"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "weekly"
- package-ecosystem: "npm" # See documentation for possible values
    directory: "/apps/webrtc-demo" # Location of package manifests
    registries: "*"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "weekly"
