name: Upload to NPM
description: Upload to the public NPM registry

# Version is taken from the package.json on the current commit, if the version is already published, the operation will fail

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: 'Version number, if provided, must match the package.json version'
      dry_run:
        type: boolean
        description: 'Skip the NPM upload step'
        default: false
    outputs:
      version:
        value: ${{ jobs.build.outputs.version }}
        description: 'The version number from the package.json'
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version number, if provided, must match the package.json version'
      dry_run:
        type: boolean
        description: 'Skip the NPM upload step'
        default: false
permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: packages/${{ env.PACKAGE }}/package-lock.json
          registry-url: https://registry.npmjs.org/
          scope: '@gcorevideo'
      - name: Check version
        id: version
        run: |
          version=${{ inputs.version }}
          pkg_version=$(jq -r '.version' packages/${{ env.PACKAGE }}/package.json)
          case "$version" in
            "" | "latest" | "$pkg_version")
              echo "INFO current version is '$pkg_version'"
              echo "version=$pkg_version" >> $GITHUB_OUTPUT
              exit 0
            ;;
            *)
              echo "ERR Version given is '$version' but version in package.json is '$pkg_version'"
              exit 1
            ;;
          esac
      - name: Install dependencies
        run: npm -C packages/${{ env.PACKAGE }} ci
      - name: Build
        run: npm -C packages/${{ env.PACKAGE }} run build
      - name: Publish
        if: inputs.dry_run != true
        run: |
          cd packages/${{ env.PACKAGE }}
          npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    env:
      PACKAGE: rtckit
