name: Publish rtckit

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  publish:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            deploy
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.2"
          cache-dependency-path: deploy/requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install -r deploy/requirements.txt
      - id: version
        name: Set version
        run: |
          version=${{ github.ref_name }}
          echo "version=${version#v}" >> $GITHUB_OUTPUT
      - name: Download dist archive
        run: |
          curl \
            -LSfs \
            -o package.tgz \
            https://registry.npmjs.org/@gcorevideo/rtckit/-/rtckit-${{ steps.version.outputs.version }}.tgz
          tar xf package.tgz
      - name: Upload to the bucket
        run: |
          LIBDIR=`pwd`/deploy
          cd package/lib
          python $LIBDIR/sri.py \
            -a sha256 \
            ./*.js > ./SHA256.txt
          python $LIBDIR/upload-s3.py \
            --endpoint https://$S3_HOSTNAME \
            --bucket rtckit \
            . \
            ${{ steps.version.outputs.version }}
        env:
          S3_HOSTNAME: ${{ secrets.S3_HOSTNAME }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
