name: Publish rtckit

on:
  push:
    tags:
      - *.*.*

jobs:
  publish:
    runs-on:
      - self-hosted-ubuntu-22-04-regular-x64
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            deploy
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.2"
          cache-dependency-path: deploy/requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install -r deploy/requirements.txt
      - name: Download dist archive
        run: |
          curl \
            -LSfs \
            -o package.tgz \
            https://registry.npmjs.org/@gcorevideo/rtckit/-/rtckit-${{ github.ref_name }}.tgz
          tar xf package.tgz
      - name: Upload to the bucket
        run: |
          LIBDIR=`pwd`/deploy
          cd package/lib
          python $LIBDIR/sri.py \
            -a sha256 \
            ./*.js > ./SHA256.txt
          python $LIBDIR/upload-s3.py \
            --endpoint 'https://$S3_HOSTNAME' \
            --bucket rtckit \
            . \
            ${{ github.ref_name }}
        env:
          S3_HOSTNAME: ${{ secrets.S3_HOSTNAME }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
